fn main() {
    tauri_build::build();
    gen_assets();
}

/// 生成 src/assets.rs：把运行时素材（图标 + 桌宠帧）编译期内嵌进 EXE。
/// 磁盘 ui/（EXE 旁）仍作为覆盖层优先（dist 布局与开发覆盖不受影响），
/// 单文件拷贝 EXE 时自动回退内嵌。
fn gen_assets() {
    use std::fmt::Write;
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let ui_root = std::path::Path::new(&manifest).join("..").join("ui");
    let out = std::path::Path::new(&manifest).join("src").join("assets.rs");

    let mut files: Vec<String> = Vec::new();
    let add = |rel: &str, files: &mut Vec<String>| {
        if ui_root.join(rel).is_file() {
            files.push(rel.to_string());
        }
    };
    for name in ["app.png", "theme-pure.png", "theme-zafkiel.png", "theme-inverse.png"] {
        add(&format!("icons/{name}"), &mut files);
    }
    add("pets/frames.json", &mut files);
    add("pets/bubbles.png", &mut files);
    let pngs = |dir: &std::path::Path, prefix: &str, files: &mut Vec<String>| {
        let Ok(rd) = std::fs::read_dir(dir) else { return };
        let mut names: Vec<String> = rd
            .filter_map(|e| e.ok().map(|e| e.file_name().to_string_lossy().to_string()))
            .filter(|n| n.ends_with(".png"))
            .collect();
        names.sort();
        for n in names {
            files.push(format!("{prefix}/{n}"));
        }
    };
    pngs(
        &ui_root.join("pets").join("kurumi").join("frames"),
        "pets/kurumi/frames",
        &mut files,
    );
    for mode in ["whale", "inverse"] {
        pngs(
            &ui_root.join("pets").join(mode).join("states"),
            &format!("pets/{mode}/states"),
            &mut files,
        );
    }

    let mut s = String::new();
    s.push_str("// Generated by build.rs — runtime-embedded asset index (do not edit)\n");
    s.push_str("// 素材编译期内嵌；运行时磁盘 ui/（EXE 旁）优先，内嵌兜底（单文件拷贝可用）。\n");
    s.push_str("pub struct Asset { pub path: &'static str, pub data: &'static [u8] }\n");
    s.push_str("pub static ASSETS: &[Asset] = &[\n");
    for f in &files {
        let esc = f.replace('\\', "/");
        let _ = writeln!(
            s,
            "    Asset {{ path: \"{esc}\", data: include_bytes!(\"../../ui/{esc}\") }},"
        );
    }
    s.push_str("];\n");
    s.push_str("pub fn find(path: &str) -> Option<&'static Asset> {\n");
    s.push_str("    ASSETS.iter().find(|a| a.path == path)\n");
    s.push_str("}\n");
    s.push_str("/// 磁盘 ui/（EXE 旁）优先（dist 布局 / 开发覆盖），内嵌兜底。\n");
    s.push_str("pub fn read(rel: &str) -> Option<Vec<u8>> {\n");
    s.push_str("    if let Ok(exe) = std::env::current_exe() {\n");
    s.push_str("        if let Some(dir) = exe.parent() {\n");
    s.push_str("            if let Ok(b) = std::fs::read(dir.join(\"ui\").join(rel)) { return Some(b); }\n");
    s.push_str("        }\n");
    s.push_str("    }\n");
    s.push_str("    find(rel).map(|a| a.data.to_vec())\n");
    s.push_str("}\n");
    std::fs::write(&out, s).expect("write src/assets.rs");
    println!(
        "[build.rs] embedded assets: {} files → src/assets.rs",
        files.len()
    );
    println!("cargo:rerun-if-changed=../ui");
    println!("cargo:rerun-if-changed=build.rs");
}
